openapi: 3.0.3
info:
  title: DropNote API
  version: 1.0.0
  description: Minimal anonymous note exchange API

servers:
  - url: http://localhost:5000/api

paths:
  /auth/session:
    post:
      summary: Create anonymous session
      responses:
        "201":
          description: Session created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"

  /notes/drop:
    post:
      summary: Drop a new note (1 per day)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewNote"
      responses:
        "201":
          description: Note created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"

  /notes/assigned:
    get:
      summary: Get a random assigned note
      responses:
        "200":
          description: Assigned note
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"

  /notes/{id}/reply:
    post:
      summary: Reply to a note (only once)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewReply"
      responses:
        "201":
          description: Reply created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reply"

  /gdpr/delete:
    delete:
      summary: Delete all my data (GDPR compliance)
      responses:
        "200":
          description: User data deleted

components:
  schemas:
    Session:
      type: object
      properties:
        sessionId:
          type: string

    NewNote:
      type: object
      properties:
        content:
          type: string
          maxLength: 500

    Note:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date-time

    NewReply:
      type: object
      properties:
        content:
          type: string
          maxLength: 300

    Reply:
      type: object
      properties:
        id:
          type: string
        noteId:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date-time
